dataset_root_dir: /scratch/luisamao/pacer_dataset

train:
  - context_data/train/marble_rock/2022-11-13-08-48-18
  - context_data/train/pebble_pavement/2022-11-13-08-50-30
  # - context_data/train/pebble_pavement/2022-11-13-08-52-08
  - context_data/train/concrete/2022-12-13-07-39-25
  - context_data/train/pebble_pavement/2022-12-13-07-51-51
  - context_data/train/grass/2022-12-13-08-03-54
  - context_data/train/bush/2022-12-14-07-57-56
  - context_data/train/bush/2022-12-14-08-00-59
  - context_data/train/yellow_brick/2022-12-14-08-05-26
  - context_data/train/marble_rock/2022-12-14-08-43-22
  # - context_data/train/marble_rock/2022-12-14-08-49-07
  - context_data/train/red_brick/2022-12-14-08-58-04
  - context_data/train/red_brick/2022-12-14-09-09-20
  - context_data/train/concrete/2022-12-15-15-21-36
  - context_data/train/grass/2022-12-15-15-32-39
  - context_data/train/pebble_pavement/2022-12-15-16-04-44
  - context_data/train/yellow_brick/2022-12-16-10-37-26
  - context_data/train/yellow_brick/2022-12-16-10-55-04
  - context_data/train/marble_rock/2022-12-16-10-58-00
  - context_data/train/red_brick/2022-12-16-11-09-30
  - context_data/train/mulch/2022-12-16-12-02-29
  - context_data/train/pebble_pavement/2023-01-18-13-41-50
  - context_data/train/grass/2023-01-18-13-54-41
  - context_data/train/concrete/2023-01-18-14-05-57
  - context_data/train/yellow_brick/2023-01-18-14-34-22
  - context_data/train/marble_rock/2023-01-18-14-41-12
  # - context_data/train/pebble_pavement/2023-01-18-14-56-25
  # - context_data/train/pebble_pavement/2023-01-25-15-49-42
  - context_data/train/grass/2023-01-25-15-54-21
  - context_data/train/pebble_pavement/2023-01-25-16-20-21

val: 
  - context_data/test/concrete/2022-12-13-07-44-22
  - context_data/test/pebble_pavement/2022-12-13-07-58-17
  - context_data/test/grass/2022-12-13-08-09-21
  - context_data/test/bush/2022-12-14-07-59-26
  - context_data/test/bush/2022-12-14-08-02-07
  - context_data/test/yellow_brick/2022-12-14-08-11-20
  - context_data/test/marble_rock/2022-12-14-08-46-15
  - context_data/test/marble_rock/2022-12-14-08-52-41
  - context_data/test/red_brick/2022-12-14-09-03-37
  - context_data/test/red_brick/2022-12-14-09-10-50
  - context_data/test/concrete/2022-12-15-15-27-03
  - context_data/test/grass/2022-12-15-15-59-39
  - context_data/test/pebble_pavement/2022-12-15-16-10-05
  - context_data/test/yellow_brick/2022-12-16-10-43-30
  - context_data/test/marble_rock/2022-12-16-11-03-19
  - context_data/test/red_brick/2022-12-16-11-14-07
  # - context_data/test/mulch/2022-12-16-12-04-46
  - context_data/test/pebble_pavement/2023-01-18-13-47-54
  - context_data/test/grass/2023-01-18-13-59-56
  - context_data/test/concrete/2023-01-18-14-25-11
  - context_data/test/marble_rock/2023-01-18-14-43-40
  - context_data/test/yellow_brick/2023-01-18-14-50-56
  - context_data/test/pebble_pavement/2023-01-18-14-58-28
  - context_data/test/pebble_pavement/2023-01-25-15-52-05
  - context_data/test/grass/2023-01-25-15-57-09
  - context_data/test/pebble_pavement/2023-01-25-16-22-57

# val:
  - context_data/test/bush/2022-12-14-08-02-07
  - context_data/test/concrete/2022-12-15-15-27-03
  - context_data/test/marble_rock/2022-12-14-08-52-41
  - context_data/test/red_brick/2022-12-14-09-10-50
  - context_data/test/pebble_pavement/2022-12-15-16-10-05
  - context_data/test/red_brick/2022-12-16-11-14-07
  - context_data/test/yellow_brick/2022-12-16-10-43-30
  - context_data/test/grass/2022-12-15-15-59-39
  - context_data/test/mulch/2022-12-16-12-04-46

# asphalt  bush  concrete  grass  marble_rock  mulch  pebble_pavement  red_brick  yellow_brick
labels:
  # - asphalt
  - bush
  - concrete
  - marble_rock
  - mulch
  - pebble_pavement
  - red_brick
  - yellow_brick
  - grass

